ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_OPENED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_CASH_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_CASH_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_CLOSED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_DIFFERENCE_RECORDED';
